### ISSUE TITLE
Improve usage of the K8sApiClient

### ISSUE THREAD

**Issue by tlake** [quintilesims/orca#34]
The first pass at the K8sApiClient saw the client being initialized once for every package that used it. As zpatrick noted [here](https://github.com/quintilesims/orca/pull/31#discussion_r225724280), it should be refactored such that it's initialized once during the app's initialization/configuration, and then that same instance is shared across instances.

- Write the client instance to redux state?
- Export/import the instantiated client?

**Comment by zpatrick** [comment]
Used a singleton instance in #37
